// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activeItem: string;
  menuItem: string;
  menuWrap: string;
  pokemonLogo: string;
  root: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
