// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'content': string;
  'fitem': string;
  'footer': string;
  'header': string;
  'logo': string;
  'menu': string;
}
export const cssExports: CssExports;
export default cssExports;
