// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  contentWrap: string;
  pokemonCards: string;
  pokemonCardsWrap: string;
  pokemonTotal: string;
  root: string;
  totalPokemonsHeader: string;
}
export const cssExports: CssExports;
export default cssExports;
